site_name: Mindustry Server Wiki
site_url: https://mopivo.github.io/wiki-serverMindustry/
repo_url: https://github.com/mopivo/wiki-serverMindustry
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: wheat
    accent: brown
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - search.highlight
  font:
    text: Roboto
    code: JetBrains Mono

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - attr_list

nav:
  - Главная: index.md
  - Установка:
    - Локальный сервер: setup/local.md
    - VPS/Dedicated: setup/vps.md
    - Docker: setup/docker.md
  - Конфигурация:
    - Базовые настройки: config/basic.md
    - Плагины: config/plugins.md
    - Брандмауэр: config/firewall.md
    - Автозапуск: config/autostart.md
  - Администрирование:
    - Команды: admin/commands.md
    - Модерация: admin/moderation.md
    - Бэкапы: admin/backups.md
  - Решение проблем:
    - Частые ошибки: troubleshooting/common-errors.md
    - Логи: troubleshooting/logs.md
    - Диагностика: troubleshooting/diagnostics.md

extra:
  generator: false
  analytics:
    provider: google
    property: UA-XXXXX-X
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mopivo/wiki-serverMindustry


copyright: |
  Created by mopivo with the support of a can of soda